{{- if .Values.kafka.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "todo-app.fullname" . }}-kafka
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
    app: kafka
spec:
  replicas: {{ .Values.kafka.replicaCount }}
  selector:
    matchLabels:
      {{- include "todo-app.selectorLabels" . | nindent 6 }}
      app: kafka
  template:
    metadata:
      labels:
        {{- include "todo-app.selectorLabels" . | nindent 8 }}
        app: kafka
    spec:
      containers:
        - name: kafka
          image: docker.redpanda.com/redpandadata/redpanda:v23.2.15
          command:
            - redpanda
            - start
            - --mode dev-container
            - --kafka-addr 0.0.0.0:9092
            - --advertise-kafka-addr PLAINTEXT://{{ include "todo-app.fullname" . }}-kafka:9092
          ports:
            - containerPort: 9092
          resources:
            {{- toYaml .Values.kafka.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-app.fullname" . }}-kafka
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 9092
      targetPort: 9092
      protocol: TCP
      name: kafka
  selector:
    {{- include "todo-app.selectorLabels" . | nindent 4 }}
    app: kafka
{{- end }}