{{- if .Values.secrets }}
{{- range $key, $value := .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $key }}
  labels:
    {{- include "todo-app.labels" $ | nindent 4 }}
type: Opaque
data:
{{- range $secretKey, $secretValue := $value.data }}
  {{ $secretKey }}: {{ $secretValue | b64enc | quote }}
{{- end }}
{{- end }}
{{- end }}